default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Blog_development
  username: postgres
  password: Duque

test:
  <<: *default
  database: Blog_test
  username: postgres
  password: Duque

production:
  <<: *default
  database: Blog_production
  username: Blog
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>